# 引入 数据库的相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 19870522
  # 配置Redis的使用
  redis:
    database: 0 # 所使用的数据库  默认是0
    host: 127.0.0.1  #所使用的redis的主机地址
    port: 6381  # 端口号  默认是 6379
    #password: zk123 # 密码
    #timeout: 5000 # 超时时间  5000毫秒
    # 连接池 lettuce 的配置
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-wait: 100000

#整合mybatis时使用的
mybatis:
  #包别名
  type-aliases-package: com.qin.entity
  #映射文件路径
  mapper-locations: classpath:com/qin/mapper/*.xml

  configuration:
    #日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

